name: CI
env: 
  SCREENER_API_KEY: ${{secrets.SCREENER_API_KEY}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  
    - name: Install Dependencies
      run: |
       #cd my-app
       npm ci
    - name: Build the app
      run: |
        #cd my-app
        npm run build --if-present
    - name: Run component tests
      run: |
        #cd my-app
        run: npm test
    - name: Start the app
      run: |
        #cd my-app
        run: npm start &
        npx wait-on  --timeout 60000
